name: recape
description: A new Flutter project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ffmpeg: ^0.4.0
  video_player: ^2.2.15
  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  table_calendar: ^3.0.9
  record: ^5.0.1
  flutter_sound_record: ^3.3.2
  just_audio: ^0.9.36
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.4
  wave: ^0.2.2
  flutter_audio_waveforms: ^1.2.1+8
  shared_preferences: ^2.2.2
  google_speech: ^5.2.0+1
  loading_indicator: ^3.1.1
 

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: NotoSans_Condensed
      fonts:
        - asset: fonts/NotoSans_Condensed-BlackItalic.ttf
        - asset: fonts/NotoSans_Condensed-BoldItalic.ttf
         

  uses-material-design: true
  
  assets:
    # - assets/images/logo_d.png
    # - assets/images/logo_l.png
    - assets/logo.mp4
    - assets/logo1.mp4
    - assets/images/logocapit.png
    - assets/images/g.png
    - assets/images/s1.jpg
    - assets/images/s5.jpg
    - assets/images/s6.jpg
    - assets/images/s7.jpg
    - assets/images/s4.jpg
   
    
